# Generated by Django 2.0.5 on 2018-07-14 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actionz',
            fields=[
                ('action_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('creator', models.CharField(default='Admin', max_length=30)),
                ('action', models.CharField(default='Empty field', max_length=200)),
                ('result', models.CharField(choices=[('None', 'None'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=256)),
                ('comment', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('checklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('checklist_name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('checkl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.CheckList')),
            ],
        ),
        migrations.AddField(
            model_name='actionz',
            name='cl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.CheckList'),
        ),
    ]
