# Generated by Django 2.0.5 on 2018-06-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_auto_20180629_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelist',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
