# Generated by Django 2.0.5 on 2018-07-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0004_auto_20180702_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zozo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoro', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='books',
            field=models.ManyToManyField(to='zone.Zozo'),
        ),
    ]
