# Generated by Django 2.0.5 on 2018-07-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0005_auto_20180703_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dota_2',
            fields=[
                ('num_of_action', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=300)),
                ('result', models.NullBooleanField()),
                ('comment', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='author',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='books',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='core_list',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='Corelist',
        ),
        migrations.DeleteModel(
            name='Zozo',
        ),
    ]
