# Generated by Django 2.0.5 on 2018-07-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0007_auto_20180708_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('expires_date', models.DateTimeField(verbose_name='expires at')),
            ],
        ),
    ]
