# Generated by Django 2.0.5 on 2018-07-07 22:03

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0008_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_details', jsonfield.fields.JSONField(unique=True)),
                ('zozo', models.CharField(max_length=40)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zone.Author')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
