# Generated by Django 2.0.5 on 2018-07-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0009_auto_20180708_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actionz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doings', models.CharField(max_length=200)),
                ('torrent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zone.Author')),
            ],
        ),
    ]
