# Generated by Django 2.0.5 on 2018-07-10 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0010_actionz'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaAuthor',
            fields=[
                ('mega_auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('mega_author_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MegaChecklist',
            fields=[
                ('mega_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('mega_checklist_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MegaSteps',
            fields=[
                ('actions_id', models.AutoField(primary_key=True, serialize=False)),
                ('actions', models.CharField(max_length=200)),
                ('mega_result', models.NullBooleanField()),
                ('mega_comment', models.CharField(blank=True, max_length=300)),
                ('bound_author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zone.MegaAuthor')),
                ('bound_checklist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zone.MegaChecklist')),
            ],
        ),
    ]
